#!/bin/bash
#
# system_info.sh — System Information Script
#
# Homework task: print the date, hostname, username, disk usage and running
# processes; use variables; take input with `read -p`; create a directory with
# `mkdir`; create a file with `touch`; and save the process list into that file
# using `>` output redirection.
#
# Usage:  ./system_info.sh
#         printf 'Kunal Kumar\n24BCS10027\nDone\nsystem_report\n' | ./system_info.sh

# ---------------------------------------------------------------
# 1. Collect the system information into VARIABLES
# ---------------------------------------------------------------
CURRENT_DATE=$(date)
HOST_NAME=$(hostname)
USER_NAME=$(whoami)
UP_TIME=$(uptime -p)
DISK_USAGE=$(df -h)
PROCESS_LIST=$(ps aux)

# ---------------------------------------------------------------
# 2. Print it, using those variables
# ---------------------------------------------------------------
echo "=================================================="
echo "            SYSTEM INFORMATION REPORT              "
echo "=================================================="
echo ""

echo "Current Date : $CURRENT_DATE"
echo "Hostname     : $HOST_NAME"
echo "Username     : $USER_NAME"
echo "Uptime       : $UP_TIME"
echo ""

echo "------------------ DISK USAGE --------------------"
echo "$DISK_USAGE"
echo ""

echo "--------- RUNNING PROCESSES (first 10) -----------"
echo "$PROCESS_LIST" | head -n 10
echo ""
echo "Total running processes: $(echo "$PROCESS_LIST" | wc -l)"
echo ""

# ---------------------------------------------------------------
# 3. Take input from the user with read -p
# ---------------------------------------------------------------
echo "=============== ENTER YOUR DETAILS ================"
read -p "Enter your name          : " NAME
read -p "Enter your roll number   : " ROLL_NO
read -p "Enter a comment          : " COMMENT
read -p "Enter a directory name   : " DIR_NAME

# Fall back to a default if the user just pressed Enter
if [ -z "$DIR_NAME" ]; then
    DIR_NAME="system_report"
    echo "No directory name entered — using the default: $DIR_NAME"
fi

echo ""
echo "My name is        : $NAME"
echo "My roll number is : $ROLL_NO"
echo "My comment is     : $COMMENT"
echo ""

# ---------------------------------------------------------------
# 4. Create the directory (mkdir) and the files (touch)
# ---------------------------------------------------------------
LOG_FILE="process.log"
INFO_FILE="system_info.txt"

mkdir -p "$DIR_NAME"
echo "Directory created : $DIR_NAME"

touch "$DIR_NAME/$LOG_FILE" "$DIR_NAME/$INFO_FILE"
echo "Files created     : $DIR_NAME/$LOG_FILE, $DIR_NAME/$INFO_FILE"
echo ""

# ---------------------------------------------------------------
# 5. Store the output in the files using > redirection
# ---------------------------------------------------------------
ps aux > "$DIR_NAME/$LOG_FILE"          #  >  overwrites the file

{                                        #  a whole block redirected at once
  echo "Report generated by : $NAME ($ROLL_NO)"
  echo "Comment             : $COMMENT"
  echo "Date                : $CURRENT_DATE"
  echo "Hostname            : $HOST_NAME"
  echo "Username            : $USER_NAME"
  echo ""
  echo "--- Disk usage ---"
  echo "$DISK_USAGE"
} > "$DIR_NAME/$INFO_FILE"

echo "Running processes saved to : $DIR_NAME/$LOG_FILE"
echo "Lines written              : $(wc -l < "$DIR_NAME/$LOG_FILE")"
echo "System info saved to       : $DIR_NAME/$INFO_FILE"
echo ""

echo "----------- First 5 lines of $LOG_FILE ------------"
head -n 5 "$DIR_NAME/$LOG_FILE"
echo ""
echo "-------------- Contents of $INFO_FILE -------------"
head -n 8 "$DIR_NAME/$INFO_FILE"
echo ""
echo "================ SCRIPT FINISHED =================="
